name: time_attendance_app
description: A time and attendance management app.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  camera: ^0.10.5+5
  path_provider: ^2.1.1
  path: ^1.8.3
  permission_handler: ^11.0.1
  geolocator: ^10.1.0
  table_calendar: ^3.0.9
  cupertino_icons: ^1.0.2
  image_cropper: ^5.0.1
  mysql1: ^0.20.0
  shared_preferences: ^2.1.0
  google_mlkit_face_detection: ^0.9.0
  google_mlkit_commons: ^0.6.1
  image: ^4.1.3
  http: ^1.1.0
  intl: ^0.18.1
  image_picker: ^1.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/icon.png"

flutter:
  uses-material-design: true
  
  assets:
    - assets/profile.png